#!/bin/bash

echo "Script all arguments $*"

########################
# Cleanup working directory
# Global:
# - HOME
# - PATH
# Arguments:
# - None
########################
clean() {
    echo "going to clean directory..."
    echo "Function first argument $1"
    echo "Function all arguments $*"
    local index=0
    for arg in "$@" ; do
        echo "Index: ${index}. Argument: ${arg}"
        (( index++ ))
    done
    echo "return value from function"
#    return 5
}

result=$(clean program1 25 98 arg4)
echo "Clean function result: ${result}"
#echo "Clean function status: $?"
